language: ruby
dist: trusty
sudo: required

matrix:
  include:
  - os: linux
    rvm: 2.1
  - os: linux
    rvm: 2.2
  - os: linux
    rvm: 2.3
  - os: linux
    rvm: 2.4.0
  - os: linux
    rvm: 2.5.0
  - os: linux
    rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
